config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  get :search, to: 'searches#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :users do
    member do
      get :set_email
      patch :confirm_email
    end
  end

  concern :likable do
    member do
      post :vote_up, :vote_down
      delete :revoke
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: %i[likable commentable], shallow: true do
    resources :answers, concerns: %i[likable commentable], except: %i[index show] do
      member do
        patch :best
      end
    end

    resources :subscriptions, only: %i[create destroy]
  end
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, shallow: true, except: %i[new] do
        resources :answers, except: %i[new]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord

  include Commentable
  include Likable

  belongs_to :user
  has_one :badge, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many_attached :files, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  after_create { subscribe(user) }

  scope :per_day, -> { where(created_at: Date.today.all_day) }

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true

  def subscribe(user)
    subscriptions.create(user: user) unless subscribed?(user)
  end

  def unsubscribe(user)
    subscriptions.find_by(user: user).destroy if subscribed?(user)
  end

  def subscribed?(user)
    subscriptions.exists?(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: %i[show update destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionShowSerializer
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question, serializer: QuestionShowSerializer
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, serializer: QuestionShowSerializer
    else
      render json: { errors: @question.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @question.destroy
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Liked

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show update destroy delete_file]
  before_action :current_user_to_gon, only: %i[index show]
  before_action :init_comment, only: %i[show update]

  after_action :publish_question, only: :create

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.links.new
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @question.badge ||= Badge.new
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if current_user.author?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Question successfully deleted.'
    end
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def current_user_to_gon
    gon.current_user = current_user
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      @question.to_json(include: :user)
    )
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      files: [],
      links_attributes: [:name, :url],
      badge_attributes: [:title, :image]
    )
  end

  def init_comment
    @comment = Comment.new
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question, class: 'hidden', html: { id: "edit-question-form" } do |f|
  = render 'shared/errors', resource: @question
  p
    = f.label :title, 'Your title'
    = f.text_field :title
  p
    = f.label :body, 'Your body'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true
  p Links:
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'add link', f, :links
  p
    = f.submit 'Save'

app/views/questions/_link_fields.html.slim
.nested-fields
  = f.label :name, 'Link name'
  = f.text_field :name
  = f.label :url
  = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/questions/_question.html.slim
- cache question do
  .title
    p= question.title

 .body
    p= question.body

  .vote
    = render 'shared/vote', resource: question

  .subscribe
    - if @question.subscribed?(current_user)
      = link_to 'Unsubscribe', subscription_path(@subscription), method: :delete, cass: 'unsubscribe-question-link'
    - else
      = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, class: 'subscribe-question-link'

- if question.badge.present?
  - cache question.badge do
    .badge
      p Badge:
      = image_tag question.badge.image, title: question.badge.title, size: "50x50"
      p = question.badge.title

- if question.links.count != 0

  .links
    p Links:
    ul
      = render question.links, resource: question

- if question.files.attached?
= render 'attachments/attachment', resource: question

.errors

- if can?(:update, question)
  = link_to 'Edit question', '#', class: 'edit-question-link'
  = render 'form'
- if can?(:destroy, question)
  = link_to 'Remove question', question_path(question), method: :delete

- if can?(:create, Comment)
  = link_to 'New comment', '#', class: 'new-comment-link', data: { klass: question.class.to_s.downcase, id: question.id }
  = render 'comments/form', resource: question

.comments
  p Comments:
  = render question.comments

app/views/questions/index.html.slim
- if can?(:create, Question)
  = link_to 'New question', new_question_path
.questions
  - @questions.each do |question|
    p= link_to question.title, question_path(question)

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p Links:
  p
    = f.fields_for :links do |l|
      = render 'link_fields', f: l
    .links
      = link_to_add_association 'add link', f, :links
  p
  p Badge:
  p
    = f.fields_for :badge do |b|
      p
        = b.label :title, 'Badge title'
        = b.text_field :title
      p
        = b.label :image
        = b.file_field :image
  p
    = f.submit 'Ask'

app/views/questions/show.html.slim
div class = "question-#{@question.id}"
  .question data-id = "#{@question.id}"
    = render @question

.answers
  = render @question.answers
    
= render 'answers/form'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('.errors').html('<%= render 'shared/errors', resource: @question %>');
<% else %>
  $('.flash').append('<%= flash_messages %>');
  $('.question').html('<%= j render @question %>');
  $('form#edit-question-form').hide()
  $('.edit-question-link').show()
<% end %>