config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  get :search, to: 'searches#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  resources :users do
    member do
      get :set_email
      patch :confirm_email
    end
  end

  concern :likable do
    member do
      post :vote_up, :vote_down
      delete :revoke
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: %i[likable commentable], shallow: true do
    resources :answers, concerns: %i[likable commentable], except: %i[index show] do
      member do
        patch :best
      end
    end

    resources :subscriptions, only: %i[create destroy]
  end
  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end

      resources :questions, shallow: true, except: %i[new] do
        resources :answers, except: %i[new]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAX_BEST_ANSWERS_COUNT = 1

  include Commentable
  include Likable

  belongs_to :question, touch: true
  belongs_to :user
  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :title, presence: true
  validate :best_count, on: :best

  after_create

  default_scope -> { order('best DESC, created_at') }
  scope :best, -> { where(best: true) }

  def best!
    transaction do
      question.answers.best.update_all(best: false)
      update!(best: true)
      user.award_badge!(question.badge) if question.badge.present?
    end
  end

  private

  def best_count
    errors.add(:answer, 'only one answer can be the best') if question.answers.best.count > MAX_BEST_ANSWERS_COUNT
  end

  def notify
    NewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Liked

  before_action :authenticate_user!
  before_action :find_question, only: :create
  before_action :find_answer, only: %i[update destroy best]
  before_action :init_comment, only: %i[create update best]

  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    flash[:notice] = 'Your answers successfully created.' if @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy
    flash[:notice] = 'Answer successfully deleted.'
  end

  def best
    @answer.best! if current_user.author?(@answer.question)
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    files = @answer.files.map { |f| { id: f.id, name: f.filename.to_s, url: url_for(f) }}

    ActionCable.server.broadcast(
      "question_#{@answer.question_id}_answers", {
        answer: @answer,
        files: files,
        links: @answer.links,
        rating: @answer.rating_sum
      }.to_json
    )
  end

  def answer_params
    params.require(:answer).permit(:title, files: [], links_attributes: [:name, :url])
  end

  def init_comment
    @comment = Comment.new
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: %i[index create]
  before_action :find_answer, only: %i[show update destroy]

  authorize_resource

  def index
    render json: @question.answers
  end

  def show
    render json: @answer, serializer: AnswerShowSerializer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, serializer: AnswerShowSerializer
    else
      render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, serializer: AnswerShowSerializer
    else
      render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @answer.destroy
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:title)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div class = "answer-#{answer.id}"
  div class = "answer-#{answer.id}-errors"

  .vote
    = render 'shared/vote', resource: answer
  
  - cache answer_cache_key(answer) do  
    - if answer.best?
      .best_answer
        h3= 'Best answer'
        p= answer.body
    - else 
      p= answer.title

  - if answer.links.count != 0
    .links
      p Links:
      ul
        = render answer.links, resource: answer

  - if answer.files.attached?
    = render 'attachments/attachment', resource: answer

  - if answer.persisted?
    - if can?(:update, answer)
      = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    - if can?(:destroy, answer)
      = link_to 'Remove answer', answer_path(answer),
        class: 'delete-answer-link',
        local: false,
        method: :delete,
        data: { answer_id: answer.id }
      
    - if can?(:best, answer) && !answer.best?
      = link_to 'Choose the best', best_answer_path(answer),
        class: 'best-answer-link',
        local: false,
        method: :patch,
        data: { answer_id: answer.id }

    - if can?(:create, Comment)
      = link_to 'New comment', '#', class: 'new-comment-link', data: { klass: answer.class.to_s.downcase, id: answer.id }
      = render 'comments/form', resource: answer

  .comments
    p Comments:
    = render answer.comments

  - cache ['edit-answer-form', answer] do
    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      = render 'shared/errors', resource: answer
      p
        = f.label :body, 'Your answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true
      p Links:
      p
        = f.fields_for :links do |l|
        .links
          = link_to_add_association 'add link', f, :links
        p
        = f.submit 'Save'

app/views/answers/_form.html.slim
- cache ['create-answer-form', @question] do
  = form_with model: [@question, @answer], html: { id: "create-answer" } do |f|
    .answer-errors
      = render 'shared/errors', resource: @answer
    p
      = f.label :title
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true
    p Links:
    p
      = f.fields_for :links do |l|
        = render 'link_fields', f: l
      .links
        = link_to_add_association 'add link', f, :links
    p
      = f.submit 'Reply'

app/views/answers/best.js.erb
$('.answers').html('<%= j render @answer.question.answers %>')

app/views/answers/create.js.erb
var flash = $('.flash')
var errors = $('.answer-errors')
<% if @answer.errors.present? %>
  errors.html('<%= render 'shared/errors', resource: @answer %>');
<% else %>
  $('.answers').append('<%= j render @answer %>');
  errors.html('');
  flash.html('');
  flash.append('<%= flash_messages %>');
  $('textarea#answer_title').val('');
  $('input#answer_links_attributes_0_name').val('');
  $('input#answer_links_attributes_0_url').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.flash').html('');
$('.flash').append('<%= flash_messages %>');
$('.answer-<%= @answer.id %>').remove();

app/views/answers/link_fields.html.slim
.nested-fields
  = f.label :name, 'Link name'
  = f.text_field :name
  = f.label :url
  = f.text_field :url
  = link_to_remove_association "remove link", f

app/views/answers/update.js.erb
<% answer_id = ".answer-#{@answer.id}" %>
var flash = $('.flash')

<% if @answer.errors.present? %>
  $('<%= answer_id+"-errors" %>').prepend('<%= render 'shared/errors', resource: @answer %>');
<% else %>
  flash.html('');
  flash.append('<%= flash_messages %>');
  $('<%= answer_id %>').html('<%= j render @answer %>');
<% end %>